apiVersion: apps/v1
kind: Deployment

metadata:
  name: footballhub-backend

spec:
  replicas: 3

  selector:
    matchLabels:
      app: footballhub-backend

  template:
    metadata:
      labels:
        app: footballhub-backend

    spec:
      containers:
        - name: footballhub-backend
          image: footballhub-backend:v3.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000